version: '3.8'

services:

  etl-video-encoding:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: etl-video-encoding
    volumes:
      - ./src:/src
    ports:
      - 4200:4200
    networks:
      - backend

  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge